{
 "title": "Exam Kubernetes - Backend Metrics",
 "tags": [
  "kubernetes",
  "prometheus",
  "backend"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "exclude_health_ready", "label": "Exclure /health et /ready", "query": "Oui:|/health|/ready,Non:" }
  ]
 },
 "panels": [
  {
   "title": "Total Requêtes (COUNT)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(http_requests_total{namespace=\"todolist\",route!~\"(/metrics${exclude_health_ready})\"}[$__range]))"
    }
   ]
  },
  {
   "title": "RPS par méthode HTTP",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (method) (rate(http_requests_total{namespace=\"todolist\",route!~\"(/metrics${exclude_health_ready})\"}[5m]))",
     "legendFormat": "{{method}}"
    }
   ]
  },
  {
   "title": "Erreurs 500 dans le temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (route, method) (increase(http_requests_total{namespace=\"todolist\",route!~\"(/metrics${exclude_health_ready})\",status=\"500\"}[1m]))",
     "legendFormat": "{{method}} {{route}}"
    }
   ]
  },
  {
   "title": "Latence p95",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum(rate(http_request_duration_seconds_bucket{namespace=\"todolist\",route!~\"(/metrics${exclude_health_ready})\"}[5m])) by (le, route)\n)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Routes et méthodes HTTP",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by (route, method) (increase(http_requests_total{namespace=\"todolist\",route!~\"(/metrics${exclude_health_ready})\"}[$__range]))"
    }
   ]
  },
  {
   "title": "Nombre de requêtes dans le temps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (method, route, status) (increase(http_requests_total{namespace=\"todolist\",route!~\"(/metrics${exclude_health_ready})\"}[1m]))",
     "legendFormat": "{{method}} {{route}} {{status}}"
    }
   ]
  }
 ]
}